# Generated by Django 4.1.1 on 2022-12-07 17:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=360)),
            ],
        ),
        migrations.CreateModel(
            name='FrontalCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=360, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrontalLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numOfLesson', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, default='', max_length=360, null=True)),
                ('presentation', models.FileField(blank=True, null=True, upload_to=main.models.upload_presentaton)),
                ('frontalCourse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frontalLessons', to='main.frontalcourse')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numOfLesson', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('link', models.CharField(max_length=100)),
                ('assignment', models.CharField(max_length=300)),
                ('answerType', models.CharField(choices=[('1', 'text'), ('2', 'link'), ('3', 'img')], default='1', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='main.course')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planName', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('briefDescription', models.CharField(blank=True, max_length=128, null=True)),
                ('link', models.URLField(blank=True, default=None, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('firstName', models.CharField(max_length=32)),
                ('lastName', models.CharField(max_length=32)),
                ('aboutMe', models.CharField(blank=True, max_length=200, null=True)),
                ('hobbies', models.CharField(blank=True, max_length=200, null=True)),
                ('badges', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('myGoal', models.CharField(blank=True, max_length=200, null=True)),
                ('userType', models.CharField(choices=[('1', 'student'), ('2', 'matatz'), ('3', 'teacher'), ('4', 'coordinator'), ('5', 'admin')], default='1', max_length=20)),
                ('mataz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matatz', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=300)),
                ('link', models.URLField(blank=True, default=None, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.upload_path)),
                ('notes', models.CharField(max_length=400)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFrontalLessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.URLField(blank=True, default=None, null=True)),
                ('exerciseGrade', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('project', models.URLField(blank=True, default=None, null=True)),
                ('projectGrade', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('frontalLesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.frontallesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFrontalCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numOfLesson', models.IntegerField()),
                ('frontalCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.frontalcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numOfLesson', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolName', models.CharField(max_length=32)),
                ('contact', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('contactPhone', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('comments', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('plan', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='main.plan')),
            ],
        ),
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='projecttsImages/')),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.project')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.ManyToManyField(related_name='groupStudents', to='main.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FrontalLessonsFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True, default=None, null=True)),
                ('frontalLesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.frontallesson')),
                ('lessonClass', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassFrontalCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.class')),
                ('frontalCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.frontalcourse')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='coordinators',
            field=models.ManyToManyField(related_name='coordinatorClasses', to='main.userprofile'),
        ),
        migrations.AddField(
            model_name='class',
            name='matazes',
            field=models.ManyToManyField(related_name='matatzClasses', to='main.userprofile'),
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='main.school'),
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(related_name='studentClasses', to='main.userprofile'),
        ),
        migrations.AddField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(related_name='teacherClasses', to='main.userprofile'),
        ),
    ]
