# Generated by Django 4.1.1 on 2023-01-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
