# Generated by Django 3.2.8 on 2021-10-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='link',
            field=models.CharField(max_length=100),
        ),
    ]
