# Generated by Django 3.2.8 on 2021-12-23 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211216_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='badges',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='myGoal',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
