# Generated by Django 3.2.8 on 2022-02-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20220120_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='userType',
            field=models.CharField(choices=[('1', 'student'), ('2', 'teacher'), ('3', 'coordinator'), ('4', 'admin')], default='1', max_length=20),
        ),
    ]
