# Generated by Django 3.2.8 on 2022-02-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_userprofile_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlessons',
            name='image',
            field=models.ImageField(blank=True, upload_to='answers/'),
        ),
        migrations.AddField(
            model_name='userlessons',
            name='link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
