# Generated by Django 3.2.8 on 2022-02-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20220227_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlessons',
            name='image',
            field=models.FileField(blank=True, upload_to='answers/'),
        ),
    ]
