# Generated by Django 3.2.8 on 2022-03-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_userlessons_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlessons',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='answers/'),
        ),
    ]
