# Generated by Django 3.2.8 on 2022-03-22 15:49

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_userlessons_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='answerType',
            field=models.CharField(choices=[('1', 'text'), ('2', 'link'), ('3', 'img')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='userlessons',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.upload_path),
        ),
    ]
