# Generated by Django 3.2.8 on 2022-04-26 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_class_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='school',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='main.school'),
        ),
    ]
