# Generated by Django 3.2.8 on 2022-04-26 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_class_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='school',
        ),
        migrations.RemoveField(
            model_name='school',
            name='Plan',
        ),
    ]
