# Generated by Django 3.2.8 on 2022-05-01 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20220426_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='PlanName',
            new_name='PlanNameeee',
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='main.school'),
        ),
        migrations.AddField(
            model_name='school',
            name='Plan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='main.plan'),
        ),
    ]
