# Generated by Django 3.2.8 on 2022-05-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20220501_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='PlanNameeee',
            new_name='planNameeee',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='Plan',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='SchoolName',
            new_name='schoolName',
        ),
    ]
