# Generated by Django 3.2.8 on 2022-05-01 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20220501_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='planNameeee',
            new_name='planName',
        ),
        migrations.AlterField(
            model_name='class',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='main.school'),
        ),
    ]
