# Generated by Django 3.2.8 on 2022-05-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20220501_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='school',
        ),
    ]
