# Generated by Django 3.2.8 on 2022-05-16 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0043_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mataz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matatz', to='auth.user'),
            preserve_default=False,
        ),
    ]
