# Generated by Django 3.2.8 on 2022-05-17 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0044_auto_20220517_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mataz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matatz', to=settings.AUTH_USER_MODEL),
        ),
    ]
