# Generated by Django 3.2.8 on 2022-05-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_userprofile_mataz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='aboutMe',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hobbies',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='myGoal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
